import "./globals.css";
import { Montserrat } from 'next/font/google';
import { Layout } from 'antd';
import BodyComponent from './component/Body';
import FooterComponent from './component/Footer';
import Link from "next/link";
import HeaderServer from "./component/HeaderServer";

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Layout>
          <HeaderServer/>
          <BodyComponent>{children}</BodyComponent>
          <FooterComponent>
            <div className="WrapperFooter">
              <h1>ARC</h1>
              <nav>
                <Link href='/' className="Links">Главная</Link>
                <Link href='/registration' className="Links">Регистрация</Link>
              </nav>
            </div>
          </FooterComponent>
        </Layout>
      </body>
    </html>
  );
}

